baseURL = "https://davidjohnston.io/"
languageCode = "en-us"
title = "David's Blog"
theme = "hemingway2"
copyright = "&copy; <a href=\"https://github.com/djohnston08\">David Johnston</a> 2017"
description = "Just some notes along the way as we figure out things for work and play."

[params]

[params.highlight]
style = "github"
languages = ["go", "dockerfile", "php", "sh"]

[[params.social]]
url = "https://github.com/djohnston08"
fa_icon = "fa-github"

[[params.social]]
url = "https://twitter.com/djohnston"
fa_icon = "fa-twitter"
