baseurl = "https://www.davidjohnston.io/"
languageCode = "en-us"
Title = "David's Blog"
# Copyright notice. This is displayer in the footer.
copyright = "&copy; <a href=\"https://github.com/djohnston08\">David Johnston</a> 2017"
theme = "hugo_theme_pickles"

[params]
  paginate = 10
  # Social accounts. Link to these accounts are displayed in the header and
  # footer
  twitter = "djohnston"
  github = "djohnston08"
  # Google Analytics API key.
  ga_api_key = "UA-110481103-1"
  author = "David Johnston"
  authorwebsite = "davidjohnston.io"
  # avatar = "/path/to/avatar"
  # contact = "https://twitter.com/djohnston"
  bio = "Father, husband, developer"
  # Short subtitle/tagline. This is displayed in the header.
  subtitle = "Random exploring of whatever interests me."
  # Logo image. This is displayed ogp image.
  logo = "/path/to/logo"
  favicon = "/path/to/favicon"

